[package]
name = "mob"
version = "0.1.0"
authors = ["Paul Diaconescu <p@afajl.com>"]
license = "MIT OR Apache-2.0"
edition = "2018"
categories = ["command-line-utilities"]
keywords = ["cli", "graphics"]
homepage = "https://github.com/afajl/mob"
readme = "README.md"

[dependencies]
chrono = { version = "0.4", features = ["serde"] }
clap = { git = "https://github.com/clap-rs/clap/" }
serde = { version = "1.0", features = ["derive"] }
confy = "0.4.0"
serde_yaml = "0.8"
serde_json = "1.0"
tempfile = "3.1.0"
log = "0.4"
anyhow = "1.0"
thiserror = "1.0"
env_logger = "0.7"
dialoguer = "0.5"
console = "0.10"
git2 = "0.13"
whoami = "0.8"
directories = "2.0"

[dev-dependencies]
mockall = "0.7"
